create_clock -name clk_27M -period 37.037 [get_ports {clk27}]
create_clock -name audio_12M288 -period 81.380208 [get_ports {clk_audio}]
create_generated_clock -name serial_126M -source [get_ports {clk27}] -multiply_by 14 -divide_by 3 [get_pins {clocks/pll/CLKOUT}]
create_generated_clock -name pixel_25M2 -source [get_pins {clocks/pll/CLKOUT}] -divide_by 5 [get_pins {clocks/divider/CLKOUT}]
create_clock -name adc_bck_clock -period 325.520833 [get_ports {adc_bck}]
set_clock_groups -asynchronous -group [get_clocks {audio_12M288}] -group [get_clocks {clk_27M serial_126M pixel_25M2}] -group [get_clocks {adc_bck_clock}]
set_false_path -from [get_ports {uart_rx reset_button}]
set_input_delay -clock adc_bck_clock -clock_fall -max 50 [get_ports {adc_lrck adc_dout}]
set_input_delay -clock adc_bck_clock -clock_fall -min -10 [get_ports {adc_lrck adc_dout}]
set_output_delay -clock adc_bck_clock -max 50 [get_ports {pcm_lrck pcm_din}]
set_output_delay -clock adc_bck_clock -min 10 [get_ports {pcm_lrck pcm_din}]
