create_clock -name clk_27M -period 37.037 [get_ports {clk27}]
create_clock -name audio_12M288 -period 81.380208 [get_ports {clk_audio}]
create_generated_clock -name sdram_12M288 -source [get_ports {clk_audio}] -divide_by 1 -invert [get_ports {O_sdram_clk}]
set_input_delay -clock [get_clocks {sdram_12M288}] -max 10 [get_ports {IO_sdram_dq[*]}]
set_input_delay -clock [get_clocks {sdram_12M288}] -min 0 [get_ports {IO_sdram_dq[*]}]
set_output_delay -clock [get_clocks {sdram_12M288}] -max 5 [get_ports {O_sdram_addr[*] O_sdram_ba[*] O_sdram_dqm[*] O_sdram_cs_n O_sdram_ras_n O_sdram_cas_n O_sdram_wen_n IO_sdram_dq[*]}]
set_output_delay -clock [get_clocks {sdram_12M288}] -min 0 [get_ports {O_sdram_addr[*] O_sdram_ba[*] O_sdram_dqm[*] O_sdram_cs_n O_sdram_ras_n O_sdram_cas_n O_sdram_wen_n IO_sdram_dq[*]}]
create_generated_clock -name serial_126M -source [get_ports {clk27}] -multiply_by 14 -divide_by 3 [get_pins {clocks/pll/CLKOUT}]
create_generated_clock -name pixel_25M2 -source [get_pins {clocks/pll/CLKOUT}] -divide_by 5 [get_pins {clocks/divider/CLKOUT}]
set_clock_groups -asynchronous -group [get_clocks {audio_12M288}] -group [get_clocks {clk_27M serial_126M pixel_25M2}]
set_false_path -from [get_ports {uart_rx reset_button}]
set_max_delay 20 -from [get_clocks {audio_12M288}] -to [get_ports {pcm_bck pcm_din pcm_lrck}]
