import {readFileSync,writeFileSync} from 'node:fs';
const palette=JSON.parse(readFileSync('shared/palette.json','utf8'));
const check=process.argv.includes('--check');
const rgb=k=>parseInt(palette.colors[k].slice(1),16);
const hex=(n,width)=>n.toString(16).padStart(width,'0');
const rgb565=k=>{const c=rgb(k);return ((c>>>19)<<11)|(((c>>>10)&63)<<5)|((c>>>3)&31);};
// M5Stack consumes R, G, B; the I2C master transmits bits 7:0 first.
// Common 1/8 intensity scaling retains hue without full-brightness LED glare.
const led=k=>{const c=rgb(k);return ((c&255)>>>3)<<16|(((c>>>8)&255)>>>3)<<8|(c>>>19);};
function output(path,content){if(check){if(readFileSync(path,'utf8').replace(/\r\n/g,'\n')!==content.replace(/\r\n/g,'\n'))throw new Error('Stale palette: '+path);}else writeFileSync(path,content);}
const cases=(fn,convert,width)=>Object.entries(palette.parameters).map(([k,ids])=>`  ${ids.join(',')}:${fn}=${width}'h${hex(convert(k),width/4)};`).join('\n');
output('fpga/rtl/control/encoder_palette.sv',`// Generated by scripts/generate-palette.mjs from shared/palette.json.\n\x60default_nettype none\nmodule encoder_palette #(parameter MAP_BITS=5)(input wire [8*MAP_BITS-1:0] mappings,output wire [191:0] led_colors);\n function automatic [23:0] led_color(input [6:0] n);\n begin case(n)\n${cases('led_color',led,24)}\n  default:led_color=24'h${hex(led('mixer'),6)};\n endcase end endfunction\n genvar g;generate for(g=0;g<8;g=g+1)begin assign led_colors[g*24+:24]=led_color(mappings[g*MAP_BITS+:MAP_BITS]);end endgenerate\nendmodule\n\x60default_nettype wire\n`);
const path='fpga/rtl/video/fabric_screen.sv';let screen=readFileSync(path,'utf8');
const branch=`function automatic [15:0] branch_color(input integer n);\n begin case(n)\n${palette.branches.map((k,i)=>`  ${i}:branch_color=16'h${hex(rgb565(k),4)};`).join('\n')}\n  default:branch_color=16'h${hex(rgb565('mixer'),4)};\n endcase end endfunction`;
const tint=`function automatic [15:0] tint(input [6:0] n);\n begin case(n)\n${cases('tint',rgb565,16)}\n  default:tint=16'h${hex(rgb565('mixer'),4)};\n endcase end endfunction`;
screen=screen.replace(/function automatic \[15:0\] branch_color\(input integer n\);[\s\S]*?endfunction/,branch).replace(/function automatic \[15:0\] tint\(input \[6:0\] n\);[\s\S]*?endfunction/,tint);
output(path,screen);
console.log(check?'PASS shared palette matches LED and HDMI tables':'Generated LED and HDMI palette');
