import {chromium} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('build',{recursive:true});
const frames=44100, wav=Buffer.alloc(44+frames*2);
wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(frames*2,40);
for(let i=0;i<frames;i++)wav.writeInt16LE(Math.round(Math.sin(2*Math.PI*440*i/44100)*4096),44+i*2);
await writeFile('build/test-44100.wav',wav);
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1536,height:1024}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
try{
 await page.goto('http://127.0.0.1:5173');await page.getByText('Rust / WASM ready',{exact:true}).waitFor();
 await page.locator('[data-bank="1"]').click();assert.equal(await page.locator('[data-encoder="encoder1"]').getAttribute('aria-label'),'encoder1 wavefolder.drive');
 await page.getByRole('button',{name:'HARDWARE',exact:true}).click();await page.locator('[data-map="encoder1"]').selectOption('vca.level');
 await page.locator('[data-bank="0"]').first().click();assert.equal(await page.locator('[data-map="encoder1"]').inputValue(),'glitch.amount');
 await page.locator('[data-bank="1"]').first().click();assert.equal(await page.locator('[data-map="encoder1"]').inputValue(),'vca.level');
 await page.getByRole('button',{name:'PATCH',exact:true}).click();await page.screenshot({path:'build/banks-web.png',fullPage:true});
 await page.locator('[data-bank="0"]').click();
 const rotary=page.locator('[data-encoder="encoder1"]');const original=Number(await rotary.getAttribute('aria-valuenow'));
 await rotary.press('ArrowUp');assert.equal(Number(await rotary.getAttribute('aria-valuenow')),original+1);
 await rotary.press('Home');assert.equal(await rotary.getAttribute('aria-valuenow'),'0');await rotary.press('End');assert.equal(await rotary.getAttribute('aria-valuenow'),'100');
 await page.locator('#sample-file').setInputFiles('build/test-44100.wav');await page.getByText('Ready · test-44100.wav · converted by Rust/WASM',{exact:true}).waitFor({timeout:30000});
 assert.match(await page.locator('#sample-info').innerText(),/44.1 → 48 kHz.*1.00 s/);
 await page.locator('#loop').uncheck();await page.locator('#play').click();await page.getByText('LOCAL DRY MONITOR',{exact:true}).waitFor();
 await page.waitForFunction(()=>!document.querySelector('#play').disabled,{timeout:5000});
 await page.getByRole('button',{name:'PERFORM',exact:true}).click();await page.getByRole('slider',{name:'filter.cutoff',exact:true}).first().fill('0.7');
 await page.getByRole('button',{name:'PATCH',exact:true}).click();
 await page.getByRole('button',{name:'Route from Sample In',exact:true}).click();await page.getByRole('button',{name:'Connect to Wavefolder',exact:true}).click();
 await page.getByRole('button',{name:'PRESETS',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#save-session').click();const download=await downloadPromise;await download.saveAs('build/test-session.json');
 const session=JSON.parse(await readFile('build/test-session.json','utf8'));assert.equal(session.patch.parameters['filter.cutoff'],.7);assert(session.patch.routes.some(r=>r[0]==='sample'&&r[1]==='wavefolder'));assert.equal(session.sample.sha256.length,64);assert.equal(session.patch.hardwareBank1.encoder1,'vca.level');
 await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"celeste-patch","version":99}')});await page.locator('#notice.error').waitFor();
 await page.locator('#import-file').setInputFiles('build/test-session.json');await page.getByText('Session restored.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'HARDWARE',exact:true}).click();await page.locator('[data-map="encoder1"]').selectOption('filter.cutoff');
 await page.getByRole('button',{name:'SETTINGS',exact:true}).click();assert.match(await page.locator('#telemetry').innerText(),/disconnected/);
 await page.getByRole('button',{name:'PATCH',exact:true}).click();await page.locator('#output-mode').selectOption('fpga');assert(await page.locator('#play').isDisabled());assert(await page.locator('#bypass').isDisabled());assert.equal(await page.locator('#bypass').getAttribute('aria-pressed'),'false');
 await page.locator('#output-mode').selectOption('monitor');await page.screenshot({path:'build/browser-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'build/browser-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'No horizontal page overflow');
 await page.setViewportSize({width:1536,height:1024});
 await page.locator('#new-patch').click();assert.equal(await page.locator('[data-node]').count(),0);
 for(const id of ['sample','mixer','out','filter'])await page.locator(`[data-select="${id}"]`).click();
 assert.equal(await page.locator('[data-node]').count(),4);
 for(const [from,to] of [['sample','filter'],['filter','mixer'],['mixer','out']]){await page.locator(`[data-out="${from}"]`).click();await page.locator(`[data-in="${to}"]`).click();}
 const heading=page.locator('[data-node="filter"] .node-heading'),box=await heading.boundingBox();
 await page.mouse.move(box.x+20,box.y+10);await page.mouse.down();await page.mouse.move(box.x+65,box.y+40,{steps:5});await page.mouse.up();
 const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('celeste-patch')));assert(saved.nodes.filter[0]>465);assert.equal(saved.routes.length,3);
 await page.reload();await page.getByText('Rust / WASM ready',{exact:true}).waitFor();assert.equal(await page.locator('[data-node]').count(),4);
 await page.locator('[data-node="filter"]').click();await page.locator('#remove-node').click();assert.equal(await page.locator('[data-node]').count(),3);
 const removed=JSON.parse(await page.evaluate(()=>localStorage.getItem('celeste-patch')));assert(!removed.routes.some(r=>r.includes('filter')));
 await page.screenshot({path:'build/editor-new-patch.png',fullPage:true});
 await page.locator('[data-select=filter]').click();await page.locator('#solo-branch').click();const isolated=JSON.parse(await page.evaluate(()=>localStorage.getItem('celeste-patch')));assert.equal(isolated.parameters['mixer.filter'],.65);assert.equal(isolated.parameters['mixer.dry'],0);await page.locator('#restore-mix').click();await page.locator('#arrange-parallel').click();assert.equal(await page.locator('[data-meter]').count(),4);await page.screenshot({path:'build/dashboard-web.png',fullPage:true});
 console.log('PASS blank patch: add, wire, drag, persist/reload, remove node and attached routes');
 await page.getByLabel('filter.mode',{exact:true}).selectOption('1');
 assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('celeste-patch'))).parameters['filter.mode'],1);
 assert.equal(await page.locator('#mod-target option').count(),1,'Only supported modulation targets are offered');
 await page.getByRole('button',{name:'PRESETS',exact:true}).click();await page.locator('[data-preset="8"]').click();
 await page.locator('[data-node="glitch"]').click();
 assert.equal(await page.getByLabel('glitch.mode',{exact:true}).inputValue(),'1');
 assert.equal(await page.getByLabel('glitch.size',{exact:true}).inputValue(),'1');
 await page.getByLabel('glitch.size',{exact:true}).selectOption('0');
 assert.match(await page.locator('[data-value="glitch.size"]').innerText(),/5.3 ms/);
 await page.getByRole('button',{name:'HARDWARE',exact:true}).click();await page.locator('[data-map="encoder1"]').selectOption('filter.mode');
 await page.reload();await page.getByText('Rust / WASM ready',{exact:true}).waitFor();
 await page.getByRole('button',{name:'HARDWARE',exact:true}).click();assert.equal(await page.locator('[data-map="encoder1"]').inputValue(),'filter.mode');
 console.log('PASS sonic web: filter selection, grain size, isolated Stutter preset, actual modulation targets, new encoder mapping persistence');
 await page.getByRole('button',{name:'PATCH',exact:true}).click();
 const patchBeforeDemo=await page.evaluate(()=>localStorage.getItem('celeste-patch'));
 await page.locator('#ambient-demo').click();
 await page.getByText('Demo ambient lista · 48 s estéreo. Pulsa Play; tu patch sigue aplicado.',{exact:true}).waitFor({timeout:60000});
 assert.match(await page.locator('#filename').innerText(),/CELESTE ambient/);
 assert.match(await page.locator('#sample-info').innerText(),/2 ch.*48.00 s/);
 assert.equal(await page.evaluate(()=>localStorage.getItem('celeste-patch')),patchBeforeDemo);
 assert(await page.locator('#loop').isChecked());
 await page.locator('#output-mode').selectOption('monitor');await page.locator('#play').click();
 await page.getByText('LOCAL DRY MONITOR',{exact:true}).waitFor();await page.locator('#stop').click();
 await page.screenshot({path:'build/ambient-demo-web.png',fullPage:true});
 console.log('PASS ambient demo: real worker generation, WAV preparation, 48-second stereo PCM, preserved patch, local playback and stop');
 assert.deepEqual(errors,[]);console.log('PASS browser: real worker/WASM WAV, resample, playback/EOF, parameters, graph, session export/import, mappings, hardware gating, responsive layout');
}finally{await browser.close();}
