// Generated by scripts/generate-palette.mjs from shared/palette.json.
`default_nettype none
module encoder_palette #(parameter MAP_BITS=5)(input wire [8*MAP_BITS-1:0] mappings,output wire [191:0] led_colors);
 function automatic [23:0] led_color(input [6:0] n);
 begin case(n)
  0,1,7,23,29,30:led_color=24'h0f0a1f;
  2,3,8:led_color=24'h1f1506;
  24,25,26:led_color=24'h1f190b;
  4,5,9,28:led_color=24'h07141f;
  11,12:led_color=24'h141b00;
  13,16:led_color=24'h170c1f;
  14,17:led_color=24'h1f0f15;
  15,31:led_color=24'h1f0e15;
  66,67,68:led_color=24'h1f1b08;
  69,70,71:led_color=24'h1f110d;
  72,73,74:led_color=24'h0b141f;
  75,77:led_color=24'h1b1d0e;
  78,79,80:led_color=24'h1f161c;
  81,82,83:led_color=24'h1f1117;
  84,85:led_color=24'h0d1a1d;
  default:led_color=24'h1b1a17;
 endcase end endfunction
 genvar g;generate for(g=0;g<8;g=g+1)begin assign led_colors[g*24+:24]=led_color(mappings[g*MAP_BITS+:MAP_BITS]);end endgenerate
endmodule
`default_nettype wire
